[project]
name = "demo"
version = "0.1"
description = "A demo library"
requires-python = ">=3.7.0"

[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "0.9"
wheel.packages = ["src/demo"]
wheel.license-files = []
